#!/usr/bin/env bash
# Switch the desktop GTK theme and light/dark preference in one place.
#
#   set-theme.sh <gtk-theme-name> [prefer-dark|prefer-light]
#   set-theme.sh NoMansSky-GTK prefer-dark
#   set-theme.sh --current            # print what is active now
#
# What this touches, and why each one is needed:
#
#   gsettings gtk-theme      -> ags picks this up (theme.ts watches the key)
#                               and GTK3 apps read it too.
#   gsettings color-scheme   -> libadwaita's light/dark, and Qt's colorScheme()
#                               when QT_QPA_PLATFORMTHEME=xdgdesktopportal.
#   gtk-{3,4}.0/settings.ini -> the fallback GTK reads when gsettings is absent.
#   gtk-{3,4}.0/gtk.css      -> the ONLY lever that reaches libadwaita apps
#                               (Nautilus et al), which ignore gtk-theme-name
#                               outright. Regenerated here.
#
# ── GTK DOES NOT LIVE-RELOAD. Measured, do not re-add the claim. ──────────────
#
# An earlier version of this file said rewriting gtk.css triggers a GTK live
# reload. It does not. Probed against GTK 3.24.52 and 4.22.4:
#
#   mutate palette.css only                       -> no change after 4s
#   mutate palette.css AND rewrite gtk.css        -> no change after 4s
#   ... plus gsettings gtk-theme Juno->Adwaita->Juno -> no change
#   GTK4, all three of the above                  -> no change after 5s
#
# Isolated: a GtkCssProvider pointed at a file never notices the file change,
# and flips the instant load_from_path() is called by hand. GtkCssProvider does
# not watch files, and nothing in the stack calls the reload. So every GTK app
# needs a RESTART for a theme change to appear. The only process that reloads
# is ags, because theme.ts re-reads gtk-theme when the gsettings key changes -
# which is why force_gsettings() below exists.

set -euo pipefail

GTK4_DIR="$HOME/.config/gtk-4.0"
GTK3_DIR="$HOME/.config/gtk-3.0"
CACHE_DIR="$HOME/.cache/themes"
LIB_DIR="$HOME/.config/themes/lib"

# Keep recolor.py from leaving a __pycache__ in the config directory.
export PYTHONDONTWRITEBYTECODE=1
IFACE="org.gnome.desktop.interface"

if [[ "${1:-}" == "--current" ]]; then
  echo "gtk-theme:    $(gsettings get $IFACE gtk-theme)"
  echo "color-scheme: $(gsettings get $IFACE color-scheme)"
  echo "icon-theme:   $(gsettings get $IFACE icon-theme)"
  exit 0
fi

THEME="${1:?usage: set-theme.sh <gtk-theme-name> [prefer-dark|prefer-light]}"
SCHEME="${2:-prefer-dark}"

# Themes live in either location; ~/.themes wins, matching GTK's own search.
THEME_DIR=""
for base in "$HOME/.themes" "$HOME/.local/share/themes" /usr/share/themes; do
  [[ -d "$base/$THEME" ]] && { THEME_DIR="$base/$THEME"; break; }
done
[[ -n "$THEME_DIR" ]] || { echo "set-theme: no such theme: $THEME" >&2; exit 1; }

PACK="$HOME/.config/themes/current"
PACK_REAL="$(readlink -f "$PACK" 2>/dev/null || true)"

# Pick the dark stylesheet only when it exists - plenty of themes ship a single
# gtk.css and no gtk-dark.css, and importing a missing file silently yields an
# unthemed window rather than an error.
pick_css() {
  local dir="$1" want_dark="$2"
  if [[ "$want_dark" == yes && -f "$dir/gtk-dark.css" ]]; then
    echo "$dir/gtk-dark.css"
  elif [[ -f "$dir/gtk.css" ]]; then
    echo "$dir/gtk.css"
  fi
}

want_dark=no
[[ "$SCHEME" == "prefer-dark" ]] && want_dark=yes

# ── Recolouring ───────────────────────────────────────────────────────────────
# palette.css only reaches a theme that references GTK's named colours. A theme
# compiled from SASS inlines its accent instead - Juno-ocean-v40 has #00A9A5 as
# a literal 112 times and mentions @theme_selected_bg_color exactly once, on
# its own @define-color line - so redefining the name does nothing at all.
#
# If the pack ships gtk-recolor.map, rewrite those literals (and the baked
# colours in the theme's PNG assets) into a copy under ~/.cache/themes and
# import that instead. ~/.themes is never modified.
RECOLOR_NOTE=""
maybe_recolor() {
  local css="$1" tag="$2"
  local map="$PACK/gtk-recolor.map"
  if [[ -z "$css" || ! -f "$map" || ! -f "$PACK/palette.css" || ! -x "$LIB_DIR/recolor.py" ]]; then
    echo "$css"; return
  fi
  local out
  if out="$("$LIB_DIR/recolor.py" "$css" "$PACK/palette.css" "$map" \
              "$CACHE_DIR/$(basename "${PACK_REAL:-pack}")/$tag" "$tag" 2>/dev/null)"; then
    echo "$out"
  else
    echo "set-theme: recolour failed for $tag, using the theme's own colours" >&2
    echo "$css"
  fi
}

write_gtk_css() {
  local outdir="$1" themesub="$2"
  local css; css="$(pick_css "$THEME_DIR/$themesub" "$want_dark")"
  css="$(maybe_recolor "$css" "$themesub")"
  # maybe_recolor runs in a command substitution, so it cannot set this itself.
  [[ "$css" == "$CACHE_DIR/"* ]] && RECOLOR_NOTE="recoloured via gtk-recolor.map"

  {
    echo "/* GENERATED by ~/.config/ags/scripts/set-theme.sh - do not edit."
    echo " * Theme: $THEME ($SCHEME)   Written: $(date -Is)"
    echo " * Hand-written rules belong in overrides.css or in the theme pack."
    echo " *"
    echo " * GTK does not live-reload this file - measured, see the header of"
    echo " * set-theme.sh. Restart a GTK app to see a change."
    echo " *"
    echo " * Import order is the cascade, last wins:"
    echo " *   1. the installed GTK theme (recoloured, if the pack maps colours)"
    echo " *   2. theme pack palette.css   - redefines @theme_bg_color etc."
    echo " *   3. overrides.css            - structural, e.g. translucency"
    echo " *   4. theme pack gtk.css       - per-theme rules, final say */"
    if [[ -n "$css" ]]; then
      # A recoloured copy has had its relative ../assets/*.png urls rewritten
      # to absolute paths, so it works from outside the theme directory.
      echo "@import url(\"file://$css\");"
    else
      echo "/* $THEME ships no $themesub stylesheet - libadwaita's default applies. */"
    fi
    # Theme pack files are optional; a missing @import silently yields an
    # unthemed window rather than an error, so only emit ones that exist.
    [[ -f "$PACK/palette.css" ]] && echo "@import url(\"file://$PACK_REAL/palette.css\");"
    echo '@import url("overrides.css");'
    [[ -f "$PACK/gtk.css" ]]     && echo "@import url(\"file://$PACK_REAL/gtk.css\");"
  } > "$outdir/gtk.css"
}

set_ini() {
  local f="$1" key="$2" val="$3"
  [[ -f "$f" ]] || printf '[Settings]\n' > "$f"
  if grep -q "^$key=" "$f"; then
    sed -i "s|^$key=.*|$key=$val|" "$f"
  else
    sed -i "0,/^\[Settings\]/s||[Settings]\n$key=$val|" "$f"
  fi
}

# gsettings emits "changed" only when the value actually DIFFERS. Measured:
#
#   set gtk-theme = Juno-ocean-v40 (already that)  -> monitor stayed silent
#   set gtk-theme = Adwaita                        -> gtk-theme: 'Adwaita'
#   set gtk-theme = Juno-ocean-v40                 -> gtk-theme: 'Juno-ocean-v40'
#
# So re-applying the SAME theme after editing palette.css never woke the ags
# bar - theme.ts's changed::gtk-theme handler simply did not run. Bouncing
# through a sentinel guarantees the signal. The sentinel is a theme name that
# does not exist, held for microseconds; nothing repaints in that window, and
# theme.ts sets the real name straight back.
#
# Only gtk-theme is bounced. color-scheme is an ENUM in the schema, so an
# invalid sentinel makes gsettings exit non-zero and would kill the script
# under `set -e`; and there is nothing to gain, since theme.ts only re-asserts
# the same AdwColorScheme on that signal.
force_gtk_theme() {
  local val="$1"
  if [[ "$(gsettings get "$IFACE" gtk-theme)" == "'$val'" ]]; then
    gsettings set "$IFACE" gtk-theme "__theme_reload__"
  fi
  gsettings set "$IFACE" gtk-theme "$val"
}

mkdir -p "$GTK4_DIR" "$GTK3_DIR" "$CACHE_DIR"
write_gtk_css "$GTK4_DIR" gtk-4.0
write_gtk_css "$GTK3_DIR" gtk-3.0

prefer_dark=false
[[ "$want_dark" == yes ]] && prefer_dark=true
for d in "$GTK4_DIR" "$GTK3_DIR"; do
  set_ini "$d/settings.ini" gtk-theme-name "$THEME"
  set_ini "$d/settings.ini" gtk-application-prefer-dark-theme "$prefer_dark"
done

force_gtk_theme "$THEME"
gsettings set "$IFACE" color-scheme "$SCHEME"

echo "set-theme: $THEME / $SCHEME${RECOLOR_NOTE:+  ($RECOLOR_NOTE)}"
echo "  gtk4 -> $(sed -n 's|^@import url("file://\(.*\)");|\1|p' "$GTK4_DIR/gtk.css" | head -1)"
echo "  gtk3 -> $(sed -n 's|^@import url("file://\(.*\)");|\1|p' "$GTK3_DIR/gtk.css" | head -1)"
